version: '3.8'

services:
  cockroach-us-east:
    image: cockroachdb/cockroach
    container_name: cockroach-us-east
    hostname: cockroach-us-east
    command:
      - start
      - --certs-dir=/cockroach/certs
      - --listen-addr=cockroach-us-east:26257
      - --advertise-addr=cockroach-us-east:26257
      - --http-addr=cockroach-us-east:8080
      - --join=cockroach-us-east:26257,cockroach-us-west:26257,cockroach-us-central:26257
      - --locality=region=us-east
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data-us-east:/cockroach/cockroach-data
      - ./certs:/cockroach/certs
    networks:
      - cockroach-network

  cockroach-us-west:
    image: cockroachdb/cockroach
    container_name: cockroach-us-west
    hostname: cockroach-us-west
    command:
      - start
      - --certs-dir=/cockroach/certs
      - --listen-addr=cockroach-us-west:26257
      - --advertise-addr=cockroach-us-west:26257
      - --http-addr=cockroach-us-west:8080
      - --join=cockroach-us-east:26257,cockroach-us-west:26257,cockroach-us-central:26257
      - --locality=region=us-west
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - cockroach-data-us-west:/cockroach/cockroach-data
      - ./certs:/cockroach/certs
    networks:
      - cockroach-network

  cockroach-us-central:
    image: cockroachdb/cockroach
    container_name: cockroach-us-central
    hostname: cockroach-us-central
    command:
      - start
      - --certs-dir=/cockroach/certs
      - --listen-addr=cockroach-us-central:26257
      - --advertise-addr=cockroach-us-central:26257
      - --http-addr=cockroach-us-central:8080
      - --join=cockroach-us-east:26257,cockroach-us-west:26257,cockroach-us-central:26257
      - --locality=region=us-central
    ports:
      - "26259:26257"
      - "8082:8080"
    volumes:
      - cockroach-data-us-central:/cockroach/cockroach-data
      - ./certs:/cockroach/certs
    networks:
      - cockroach-network

  # Config Servers
  config1:
    image: mongo:latest
    container_name: config1
    command: mongod --configsvr --replSet configReplSet --port 27019
    ports:
      - "27019:27019"
    volumes:
      - config1_data:/data/db
    networks:
      - mongo_cluster

  config2:
    image: mongo:latest
    container_name: config2
    command: mongod --configsvr --replSet configReplSet --port 27019
    networks:
      - mongo_cluster
    volumes:
      - config2_data:/data/db

  config3:
    image: mongo:latest
    container_name: config3
    command: mongod --configsvr --replSet configReplSet --port 27019
    networks:
      - mongo_cluster
    volumes:
      - config3_data:/data/db

  # Shard 1
  us_east_1:
    image: mongo:latest
    container_name: us_east_1
    command: mongod --shardsvr --replSet us_eastReplSet --port 27018
    ports:
      - "27018:27018"
    volumes:
      - us_east_1_data:/data/db
    networks:
      - mongo_cluster

  us_east_2:
    image: mongo:latest
    container_name: us_east_2
    command: mongod --shardsvr --replSet us_eastReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_east_2_data:/data/db

  us_east_3:
    image: mongo:latest
    container_name: us_east_3
    command: mongod --shardsvr --replSet us_eastReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_east_3_data:/data/db

  # Shard 2
  us_west_1:
    image: mongo:latest
    container_name: us_west_1
    command: mongod --shardsvr --replSet us_westReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_west_1_data:/data/db

  us_west_2:
    image: mongo:latest
    container_name: us_west_2
    command: mongod --shardsvr --replSet us_westReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_west_2_data:/data/db

  us_west_3:
    image: mongo:latest
    container_name: us_west_3
    command: mongod --shardsvr --replSet us_westReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_west_3_data:/data/db

  # Shard 3
  us_central_1:
    image: mongo:latest
    container_name: us_central_1
    command: mongod --shardsvr --replSet us_centralReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_central_1_data:/data/db

  us_central_2:
    image: mongo:latest
    container_name: us_central_2
    command: mongod --shardsvr --replSet us_centralReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_central_2_data:/data/db

  us_central_3:
    image: mongo:latest
    container_name: us_central_3
    command: mongod --shardsvr --replSet us_centralReplSet --port 27018
    networks:
      - mongo_cluster
    volumes:
      - us_central_3_data:/data/db
  
  # Mongos 1
  mongos1:
    image: mongo:latest
    container_name: mongos1
    command: mongos --configdb configReplSet/config1:27019,config2:27019,config3:27019 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo_cluster
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - config1
      - config2
      - config3
      - us_east_1
      - us_west_1
      - us_central_1

  # Mongos 2 (New Instance)
  mongos2:
    image: mongo:latest
    container_name: mongos2
    command: mongos --configdb configReplSet/config1:27019,config2:27019,config3:27019 --port 27017 --bind_ip_all
    ports:
      - "37017:27017"
    networks:
      - mongo_cluster
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - config1
      - config2
      - config3
      - us_east_1
      - us_west_1
      - us_central_1

volumes:
  cockroach-data-us-east:
  cockroach-data-us-west:
  cockroach-data-us-central:
  config1_data:
  config2_data:
  config3_data:
  us_east_1_data:
  us_east_2_data:
  us_east_3_data:
  us_west_1_data:
  us_west_2_data:
  us_west_3_data:
  us_central_1_data:
  us_central_2_data:
  us_central_3_data:

networks:
  cockroach-network:
  mongo_cluster:
    driver: bridge